(library
 (name dox_native)
 (wrapped false)
 (modules dox_native)
 (foreign_stubs
  (language c)
  (names dox_openat)))

(executable
 (name main)
 (public_name dox)
 (modules
  util
  module_path
  observation
  document
  page_index
  module_graph
  diff
  evaluator
  debugger
  compiler_workspace
  project
  server
  main)
 (libraries unix str yojson dox_native))

(test
 (name test_document)
 (modules test_document util module_path document)
 (libraries unix str yojson))

(test
 (name test_project)
 (modules
  test_project
  util
  module_path
  observation
  document
  page_index
  module_graph
  diff
  evaluator
  debugger
  compiler_workspace
  project
  server)
 (libraries unix str yojson dox_native))

(test
 (name test_evaluator)
 (modules
  test_evaluator
  util
  module_path
  observation
  document
  evaluator
  debugger)
 (libraries unix str yojson))

(test
 (name test_workspace)
 (modules
  test_workspace
  util
  module_path
  observation
  document
  page_index
  module_graph
  diff
  evaluator
  compiler_workspace
  project)
 (libraries unix str yojson dox_native))
