(library
 (name doclang_native)
 (wrapped false)
 (modules doclang_native)
 (foreign_stubs
  (language c)
  (names doclang_openat)))

(executable
 (name main)
 (public_name doclang)
 (modules
  util
  module_path
  observation
  document
  page_index
  module_graph
  diff
  evaluator
  compiler_workspace
  project
  server
  main)
 (libraries unix str yojson doclang_native))

(test
 (name test_document)
 (modules test_document util module_path document)
 (libraries unix str yojson))

(test
 (name test_project)
 (modules
  test_project
  util
  module_path
  observation
  document
  page_index
  module_graph
  diff
  evaluator
  compiler_workspace
  project
  server)
 (libraries unix str yojson doclang_native))

(test
 (name test_evaluator)
 (modules test_evaluator util module_path observation document evaluator)
 (libraries unix str yojson))

(test
 (name test_workspace)
 (modules
  test_workspace
  util
  module_path
  observation
  document
  page_index
  module_graph
  diff
  evaluator
  compiler_workspace
  project)
 (libraries unix str yojson doclang_native))
