(executable
 (name main)
 (public_name doclang)
 (modules util observation document diff evaluator project server main)
 (libraries unix str yojson))

(test
 (name test_document)
 (modules test_document util document)
 (libraries unix str yojson))

(test
 (name test_project)
 (modules test_project util observation document diff evaluator project)
 (libraries unix str yojson))

(test
 (name test_evaluator)
 (modules test_evaluator util observation document evaluator)
 (libraries unix str yojson))
